### ISSUE TITLE
Prepare different builds

### ISSUE THREAD

**Issue by motoharu-gosuto** [motoharu-gosuto/psvpfstools#17]
Win7 0x32
Win7 0x64
WinXP 0x32
WinXP 0x64
Ubuntu 0x32
Ubuntu 0x64

**Comment by SilicaAndPina** [comment]
Wont anything that runs on WinXP run on Win7 and up anyway?

**Comment by motoharu-gosuto** [comment]
@SilicaAndPina 
I dont think so.  Maybe in compatibility mode or smth?
Usually you use different toolset to compile for XP and for Win7.

**Comment by motoharu-gosuto** [comment]
Windows builds done

**Comment by tomazzz369** [comment]
unfortunately WinXP 0x32 not working on win xp 32 bit sp3

"Entry Point Not Found InitializeCriticalSectionEX in the library KERNEL32.dll"

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
This is really weird. Despite the fact that I have built it with xp toolchain.

**Comment by tomazzz369** [comment]
ok, first of all i never used cmake before. first i run your bat build_win32_xp.bat (i needed to remove -DBOOST_MODEL_TAG="-x32" because of warning), later i open the project in visual studio 2012 and i build app. i have 'release' build working fine on xp (compiled on win7 x64 with wisual studio 2012). seems to, everything is fine. tested one app, update, theme, and dlc

now, how can i set Multi-threaded (/MT) instead Multi-threaded DLL (/MD) because if i change that in project i have libs conflict

>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library 1

btw why release_win32_7 not working on win7 x64 - app crash. release_win64_7 working fine, weird because both builds should worked on win7 x64 (x86 and x64)

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
About release_win32_7  - this is strange. It works just fine on my Win7 x64 machine. What type of crash are you experiencing?

About runtime - you can not mix static and dynamic runtime. If you are going to compile with static runtime - you have to change settings in all 4 projects.
Probably you will also have to compile boost, curl and zlib with static runtime as well. It is not that easy.

**Comment by tomazzz369** [comment]
this is my build working on win xp 32 bit sp3

`http://www116.zippyshare.com/v/V70TDZi5/file.html`

Successfully decompressed zRIF from provided license string.
parsing  files.db...
verifying header...
header signature is valid
root icv is valid
Validating hash tree...
Hash tree is ok
Building directory matrix...
Building file matrix...
Flattening file pages...
Building dir paths...
Building file paths...
Linking dir paths...
Linking file paths...
Matching file paths...
parsing  unicv.db...
Total blocks: 40
Building unicv.db -> files.db relation...
Match found: 2 PCSB00094/sce_sys/param.sfo
Match found: 4 PCSB00094/sce_sys/clearsign
Match found: 6 PCSB00094/sce_sys/keystone
Match found: 8 PCSB00094/STARWARS_Rebels.pxp
Creating directories...
Created: PCSB00094/sce_sys
Creating empty files...
Decrypting files...
Copied: PCSB00094/sce_sys/param.sfo
Copied: PCSB00094/sce_sys/clearsign
Decrypted: PCSB00094/sce_sys/keystone
Decrypted: PCSB00094/STARWARS_Rebels.pxp
keystone sanity check...
keystone: matched retail hmac

**Comment by motoharu-gosuto** [comment]
@tomazzz369 
Thanks! I will add this build to the release page.
