### ISSUE TITLE
THROPHY.TRP not found?

### ISSUE THREAD

**Issue by Mc-muffin** [motoharu-gosuto/psvpfstools#32]
So, while I was trying to decrypt a game update (PCSE01116 | Undertale v1.04 ) the tool showed (as expected):

 ```
Building unicv.db -> files.db relation...
File ./PCSE01116/sce_sys/about/right.suprx is empty
File ./PCSE01116/sce_sys/keystone is empty
File ./PCSE01116/sce_sys/trophy/NPWR13830_00/TROPHY.TRP is empty
Match found: 6 ./PCSE01116/sce_sys/param.sfo
Match not found: 8
```

Previously I just used the base game files instead of the 0kb that the update has but now it shows this:

```
parsing  files.db...
verifying header...
header signature is valid
root icv is valid
Validating hash tree...
0 - OK : 945a2352790f9020f21d42a8c677caf26c19e31a
1 - OK : 54778d3d4ee5bf66d3ff7c872097a5fc81386e10
3 - OK : 917e2bf5896ff7c1444b41537279d82f233b75a6
Hash tree is ok
Building directory matrix...
Building file matrix...
Flattening file pages...
Building dir paths...
Building file paths...
Linking dir paths...
Linking file paths...
Matching file paths...
parsing  unicv.db...
Total blocks: 71
Building unicv.db -> files.db relation...
Match found: 6 ./PCSE01116/sce_sys/param.sfo
Match found: 8 ./PCSE01116/sce_sys/about/right.suprx
Match found: a ./PCSE01116/sce_sys/changeinfo/changeinfo.xml
Match found: c ./PCSE01116/sce_sys/changeinfo/changeinfo_00.xml
Match found: e ./PCSE01116/sce_sys/clearsign
Match found: 10 ./PCSE01116/sce_sys/keystone
Match not found: 12
```

I'm fairly certain that the unmatched file is the TROPHY.TRP file, but why? Any idea what's happening?

**Comment by tomazzz369** [comment]
use latest update 1.08, i can't check update 1.04 because i don't have link

update 1.08:

Klicensee: C8FC673C6656B0F4C646FA0008D1738E
Parsing files.db...
Verifying header...
Header signature is valid
Root icv is valid
Validating hash tree...
0 - OK : c5c051e0d9d4bbf7c686909436bfca8ba09d6fba
1 - OK : d631bd9c2784d0f658f2fa2365ac33c0cdd8d2c3
3 - OK : 40010714eef8ecf78c423c8abee2fa1562e9c617
Hash tree is ok
Building directory matrix...
Building file matrix...
Flattening file pages...
Building dir paths...
Building file paths...
Linking dir paths...
Linking file paths...
Matching file paths...
Parsing unicv.db...
Total blocks: 71
Building unicv.db -> files.db relation...
Match found: 6 UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/param.sfo
Match found: 8 UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/about/right.suprx
Match found: a UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/changeinfo/changeinfo.xml
Match found: c UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/changeinfo/changeinfo_00.xml
Match found: e UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/clearsign
Match found: 10 UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/keystone
Match found: 12 UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/trophy/NPWR13830_00/TROPHY.TRP
Match found: 15 UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_module/libc.suprx
Match found: 17 UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_module/libfios2.suprx
Match found: 19 UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_module/libult.suprx
Match found: 1b UP3893-PCSE01116_00-TFSHVCUTPSV00084/eboot.bin
Match found: 1f UP3893-PCSE01116_00-TFSHVCUTPSV00084/games/game.win
Creating directories...
Created: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys
Created: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/about
Created: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/changeinfo
Created: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/trophy
Created: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/trophy/NPWR13830_00
Created: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_module
Created: UP3893-PCSE01116_00-TFSHVCUTPSV00084/games
Creating empty files...
Decrypting files...
Copied: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/param.sfo
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/about/right.suprx
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/changeinfo/changeinfo.xml
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/changeinfo/changeinfo_00.xml
Copied: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/clearsign
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/keystone
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/trophy/NPWR13830_00/TROPHY.TRP
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_module/libc.suprx
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_module/libfios2.suprx
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_module/libult.suprx
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/eboot.bin
Decrypted: UP3893-PCSE01116_00-TFSHVCUTPSV00084/games/game.win
Keystone sanity check...
Keystone: matched retail hmac
F00D cache:

**Comment by tomazzz369** [comment]
never mind, i found, you use incremental update

**this is not a psvpfstools issue**

Klicensee: C8FC673C6656B0F4C646FA0008D1738E
Parsing files.db...
Verifying header...
Header signature is valid
Root icv is valid
Validating hash tree...
0 - OK : 945a2352790f9020f21d42a8c677caf26c19e31a
1 - OK : 54778d3d4ee5bf66d3ff7c872097a5fc81386e10
3 - OK : 917e2bf5896ff7c1444b41537279d82f233b75a6
Hash tree is ok
Building directory matrix...
Building file matrix...
Flattening file pages...
Building dir paths...
Building file paths...
Linking dir paths...
Linking file paths...
Matching file paths...
Parsing unicv.db...
Total blocks: 71
Building unicv.db -> files.db relation...
File UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/about/right.suprx is empty
File UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/keystone is empty
File UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/trophy/NPWR13830_00/TROPHY.TRP
 is empty
Match found: 6 UP3893-PCSE01116_00-TFSHVCUTPSV00084/sce_sys/param.sfo
Match not found: 8

**Comment by Mc-muffin** [comment]
Oh, so if this is not a psvpfstools issue, there's no way to decrypt these incremental update files on pc? Updates prior (like v1.03, which don't have this trophy file at all) seem to work just fine.

**Comment by tomazzz369** [comment]
of course there is a way, but if you don't have full patch cumulative/hybrid_package, you need to download patch 1.01, 1.02 and 1.03, extract all updates, remove empty files in updates 1.02 and 1.03 and overwrite patch 1.01 with newer/updated files to get working 1.03 update and then use psvpfstools

weird, because i have trophy file in update 1.03

**Comment by Mc-muffin** [comment]
Okay I feel stupid now, I was pulling the wrong trophy.trp and that was causing it to not extract the update. I'll close this issue now, thanks again!
